import type { Metadata } from "next";
import { Exo, Geist, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "./_myComponents/footer/page";
import NavBar from "./_myComponents/NavBar/page";
import SessionProviderServer from "./_myComponents/SessionProvider/SessionProviderServer";
import FeaturesSection from "@/components/FeaturesSection";
import { Toaster } from "sonner";


const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const exo = Exo({
  subsets: ["latin"],
});
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
  icons:
{
  icon:"/favicon.svg",
}};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, "font-sans", inter.variable)}
    >
      <body className={`min-h-full flex flex-col  ${exo.className}`}>
        <SessionProviderServer>
        <NavBar />
      <main className=" flex-1 mb-0">
    {children}
     <Toaster  />
      <FeaturesSection />
    
  </main>
   
        </SessionProviderServer>
        <Footer />
      </body>
    </html>
  );
}
